name: ${PROJECT_NAME}

services:
  database:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
    ports:
      - '${DB_PORT:-3306}:3306'
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: wp-template-custom:latest
    container_name: ${PROJECT_NAME}_app
    restart: always
    depends_on:
      - database
    ports:
      - '${WP_PORT:-8080}:80'
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DEBUG: '1'
      WORDPRESS_DEBUG_LOG: '1'
      WORDPRESS_DEBUG_DISPLAY: '1'
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    networks:
      - wp_network
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - '${PMA_PORT:-8081}:80'
    env_file:
      - ./.env
    environment:
      PMA_HOST: database:3306
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wp_network
volumes:
  db_data:
  wordpress_data:
networks:
  wp_network:
